const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  scanLibrary: (options) => ipcRenderer.invoke('library:scan', options),
  getCachedLibrary: () => ipcRenderer.invoke('library:cached'),
  onLibraryProgress: (callback) => { const listener = (_event, data) => callback(data); ipcRenderer.on('library:progress', listener); return () => ipcRenderer.removeListener('library:progress', listener); },
  onLibraryInitial: (callback) => { const listener = (_event, data) => callback(data); ipcRenderer.on('library:initial', listener); return () => ipcRenderer.removeListener('library:initial', listener); },
  onLibraryTrending: (callback) => { const listener = (_event, data) => callback(data); ipcRenderer.on('library:trending', listener); return () => ipcRenderer.removeListener('library:trending', listener); },
  onLibraryArtwork: (callback) => { const listener = (_event, data) => callback(data); ipcRenderer.on('library:artwork', listener); return () => ipcRenderer.removeListener('library:artwork', listener); },
  launchGame: (gameId, launchOptions) => ipcRenderer.invoke('game:launch', gameId, launchOptions),
  launchSteamBigPicture: (gameId) => ipcRenderer.invoke('launcher:steam-big-picture', gameId),
  saveGameLaunchOptions: (gameId, options) => ipcRenderer.invoke('game:launch-options:save', gameId, options),
  saveGameCategory: (gameId, isApp) => ipcRenderer.invoke('game:category:save', gameId, isApp),
  gameAction: (gameId, action) => ipcRenderer.invoke('game:action', gameId, action),
  searchArtwork: (query, gameId) => ipcRenderer.invoke('artwork:search', query, gameId),
  getOfficialSteamArtwork: (gameId, appId) => ipcRenderer.invoke('artwork:official-steam', gameId, appId),
  getCatalogArtwork: (title, source) => ipcRenderer.invoke('artwork:catalog-choices', title, source),
  saveArtwork: (gameId, selection) => ipcRenderer.invoke('artwork:save', gameId, selection),
  refreshGameArtwork: (gameId) => ipcRenderer.invoke('artwork:refresh-one', gameId),
  getGameLogo: (gameId) => ipcRenderer.invoke('artwork:logo', gameId),
  getGameNews: (gameId) => ipcRenderer.invoke('news:get', gameId),
  getGameDetails: (gameId) => ipcRenderer.invoke('game:details', gameId),
  getSteamDiscovery: () => ipcRenderer.invoke('steam:discovery'),
  onSteamDiscoveryArtwork: (callback) => { const listener = (_event, data) => callback(data); ipcRenderer.on('steam:discovery-artwork', listener); return () => ipcRenderer.removeListener('steam:discovery-artwork', listener); },
  getSteamDiscoveryDetails: (appId) => ipcRenderer.invoke('steam:discovery-details', appId),
  openSteamStore: (appId) => ipcRenderer.invoke('steam:open-store', appId),
  getOwnedDlc: (gameId) => ipcRenderer.invoke('game:owned-dlc', gameId),
  getGameAchievements: (gameId) => ipcRenderer.invoke('game:achievements', gameId),
  openTrueAchievements: (gameId) => ipcRenderer.invoke('achievements:open-trueachievements', gameId),
  saveAchievementReference: (gameId, appId) => ipcRenderer.invoke('game:achievement-reference:save', gameId, appId),
  saveXboxAchievementReference: (gameId, reference) => ipcRenderer.invoke('game:xbox-achievement-reference:save', gameId, reference),
  openNews: (url) => ipcRenderer.invoke('news:open', url),
  addGame: () => ipcRenderer.invoke('game:add'),
  bulkAddGames: () => ipcRenderer.invoke('game:bulk-add'),
  saveCustomGame: (game) => ipcRenderer.invoke('game:custom:save', game),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  getSteamLocalStatus: () => ipcRenderer.invoke('steam:local-status'),
  chooseEpicHelper: () => ipcRenderer.invoke('epic:choose-helper'),
  getEpicHelperStatus: (configuredPath) => ipcRenderer.invoke('epic:helper-status', configuredPath),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  clearCustomArtwork: () => ipcRenderer.invoke('settings:clear-custom-artwork'),
  resetLauncherData: () => ipcRenderer.invoke('settings:reset-all'),
  previewScale: (value) => ipcRenderer.invoke('settings:preview-scale', value),
  openSteamHelp: (destination) => ipcRenderer.invoke('steam:open-help', destination),
  openFeedback: () => ipcRenderer.invoke('app:feedback'),
  openFseSetup: () => ipcRenderer.invoke('app:fse-setup'),
  minimizeLauncher: () => ipcRenderer.invoke('app:minimize-to-taskbar'),
  quit: () => ipcRenderer.invoke('app:quit')
});
